name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
            
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@7.0.1
            
        with:
          switches: -avzr --delete
          path: ./code/*
          remote_path: /var/www/html
          remote_host:  "${{ secrets.HOST }}"
          remote_user: "${{ secrets.USER }}"
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
